server:
  port: 8083
  
eureka:  instance:    hostname: localhost
  client:    service-url:
      defaultZone: http://localhost:8761/eureka
    
spring:  application:    name: api-gateway
      cloud:    gateway:      routes:      - id: user-service
        uri: lb://USER-SERVICE
        predicates:        - Path=/user/**
        
      - id: security-service
        uri: lb://SECURITY-SERVICE
        predicates:
        - Path=/security/**
        
      - id: advertisement-service
        uri: lb://ADVERTISEMENT-SERVICE
        predicates:        - Path=/advertisement/**
        
      - id: complaint-service  
        uri: lb://COMPLAINT-SERVICE
        predicates:        - Path=/complaint/**
      - id: secureuser-service
        uri: lb://SECUREUSER-SERVICE
        predicates:        - Path=/secureuser/**                    